
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Praktikum extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum
     */
    public Praktikum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtjumat = new javax.swing.JTextField();
        jtxtsenin = new javax.swing.JTextField();
        jtxtselasa = new javax.swing.JTextField();
        jtxtrabu = new javax.swing.JTextField();
        jtxtkamis = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jcokelas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Jadwal Pelajaran Kelas XI RPL 1 - XI RPL 3");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 300, 20);

        jLabel3.setText("Jum'at");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 310, 50, 14);

        jLabel4.setText("Senin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 150, 50, 14);

        jLabel5.setText("Selasa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 190, 50, 14);

        jLabel6.setText("Rabu");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 230, 60, 14);

        jLabel7.setText("Kamis");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 270, 50, 14);

        jtxtjumat.setEditable(false);
        getContentPane().add(jtxtjumat);
        jtxtjumat.setBounds(140, 300, 290, 30);

        jtxtsenin.setEditable(false);
        getContentPane().add(jtxtsenin);
        jtxtsenin.setBounds(140, 140, 290, 30);

        jtxtselasa.setEditable(false);
        getContentPane().add(jtxtselasa);
        jtxtselasa.setBounds(140, 180, 290, 30);

        jtxtrabu.setEditable(false);
        getContentPane().add(jtxtrabu);
        jtxtrabu.setBounds(140, 220, 290, 30);

        jtxtkamis.setEditable(false);
        getContentPane().add(jtxtkamis);
        jtxtkamis.setBounds(140, 260, 290, 30);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 130, 410, 240);

        jcokelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kelas Anda-", "XI RPL 1", "XI RPL 2", "XI RPL 3" }));
        jcokelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcokelasActionPerformed(evt);
            }
        });
        jPanel1.add(jcokelas);
        jcokelas.setBounds(200, 90, 140, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Pilih Kelas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 90, 70, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 440);

        setBounds(0, 0, 493, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void jcokelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcokelasActionPerformed

        // TODO add your handling code here:
        if(jcokelas.getSelectedItem().equals("XI RPL 1")){
           jtxtsenin.setText("Seni Budaya, B.Inggris, PPB, PKn, PPL");
           jtxtselasa.setText("Olahraga, Sejarah, B.Indo, RBJ, Agama");
           jtxtrabu.setText("Basdat, PKWU, Admin Server, WebDinamis");
           jtxtkamis.setText("MAT, Fisika, Sistel, B.Jawa, Agama");
           jtxtjumat.setText("PBO, BK, Desktop, PPB");
        }
        else  if(jcokelas.getSelectedItem().equals("XI RPL 2")){
           jtxtsenin.setText("Olahraga, Sejarah, B.Indo, RBJ, Agama");
           jtxtselasa.setText("PBO, BK, Desktop, PPB");
           jtxtrabu.setText("MAT, Fisika, Sistel, B.Jawa, Agama");
           jtxtkamis.setText("Basdat, PKWU, Admin Server, WebDinamis");
           jtxtjumat.setText("Seni Budaya, B.Inggris, PPB, PKn, PPL");
        }
        else if(jcokelas.getSelectedItem().equals("XI RPL 3")){
         jtxtsenin.setText("Agama, PKN, B.Indonesia, Basdat");
           jtxtselasa.setText("MTK, Desktop, PPL, BInggris");
           jtxtrabu.setText("Sejarah, RBJ, PKWU, Fisika, Desktop");
           jtxtkamis.setText("Seni Budaya, Olahraga, Admin Server, BK, PPB");
           jtxtjumat.setText("PBO, PWD, Agama, B.Jawa");
    }
    }//GEN-LAST:event_jcokelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcokelas;
    private javax.swing.JTextField jtxtjumat;
    private javax.swing.JTextField jtxtkamis;
    private javax.swing.JTextField jtxtrabu;
    private javax.swing.JTextField jtxtselasa;
    private javax.swing.JTextField jtxtsenin;
    // End of variables declaration//GEN-END:variables
}
